from animals_collateral_adjectives_collector.animal_image_collector import fetch_animal_images,fetch_og_image, save_image
from animals_collateral_adjectives_collector.data_collector import collect_collateral_adjectives
from animals_collateral_adjectives_collector.html_generator import render_animal_table
from animals_collateral_adjectives_collector.logging_config import configure_logging
