from animals_collateral_adjectives_collector.image_fetcher import fetch_animal_images,fetch_og_image
from animals_collateral_adjectives_collector.collateral_adjectives_collector import collect_collateral_adjectives, populate_collateral_map
from animals_collateral_adjectives_collector.html_generator import render_animal_table
from animals_collateral_adjectives_collector.logging_config import configure_logging
from animals_collateral_adjectives_collector.image_processing import process_images
from animals_collateral_adjectives_collector.collateral_adjectives_table_parser import get_column_indices, parse_animal, parse_collateral_adjective